## Data Cleansing

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
filenames = os.listdir('./PycharmProjects/rateMyProf/')
filenames

['.Allred.csv',
 '.Bahmmerman.csv',
 '.Barkatt.csv',
 '.Brown.csv',
 '.Chadwick.csv',
 '.Chiwocha.csv',
 '.Coombe.csv',
 '.Cooper.csv',
 '.Coopersmith.csv',
 '.Fabian.csv',
 '.Fields.csv',
 '.Frankel.csv',
 '.Garcia.csv',
 '.Giordani.csv',
 '.Gracia.csv',
 '.Grafe.csv',
 '.Gregorian.csv',
 '.Harolovich.csv',
 '.Hawkins.csv',
 '.Haynes.csv',
 '.Heimgartner.csv',
 '.Holtman.csv',
 '.Huey.csv',
 '.Jacobson.csv',
 '.Jameson.csv',
 '.Joachim.csv',
 '.Kelly.csv',
 '.Krantz.csv',
 '.Lee.csv',
 '.Ligon.csv',
 '.McVey.csv',
 '.Mello.csv',
 '.Minner.csv',
 '.Monnette.csv',
 '.Padovano.csv',
 '.Peikes.csv',
 '.Percy.csv',
 '.Pfau.csv',
 '.Phillips.csv',
 '.Reifler.csv',
 '.Robertson.csv',
 '.Rogers.csv',
 '.Savage-Dun.csv',
 '.Sewell.csv',
 '.Smarook.csv',
 '.Splitter.csv',
 '.Sultan.csv',
 '.Symanski.csv',
 '.Thompson- Brieg.csv',
 '.Tindell.csv',
 '.Vargas.csv',
 '.Waggett.csv',
 'A JSenchack.csv',
 'A. E.Stiegman.csv',
 'A. J.Grant.csv',
 'A.Benitez.csv',
 'A.Galantowicz.csv',
 'A.Paul.csv',
 'AaronCulley.csv',
 'AaronFogel.csv',
 'AaronGreer.csv',
 'AaronKozbelt.csv',
 'AaronLatham.csv',
 'AaronLowen.csv',
 'AaronYoung.csv',
 'AbbasForoughi.csv',
 'AbdelnourAhmed-Zaid.csv',
 'AbdieTabrizi.csv',
 'AbdolrezaAbhari.csv',
 'AbdoumaliqSimone.csv',
 'AbdusamadKabir.csv',
 'AbiAwomolo.csv',
 'AbrahamTeng.csv',
 'AChiang.csv',
 'AchSen.csv',
 'AcReeves.csv',
 'AdamBurgener.csv',
 'AdamCohen.csv',
 'AdamHelfer.csv',
 'AdamMyers.csv',
 'Adel SSedra.csv',
 'AdelaDe La Torre.csv',
 'AdeleLindenmeyr.csv',
 'AdeleMueller.csv',
 'AdesijiAtekoja.csv',
 'AdrianNachman.csv',
 'AdrianRoitberg.csv',
 'AdrienneSu.csv',
 'AfaaWeaver.csv',
 'AgashiNwogbaga.csv',
 'AgnieskaWozniciewicz.csv',
 'Ahmad FaroughVakil.csv',
 'AhmedAmeur.csv',
 'AhsanHabib.csv',
 'AidenKenny.csv',
 'AimeeMiller.csv',
 'AimeeShouse.csv',
 'AjoyDatta.csv',
 'AKarim.csv',
 'AlainChalifour.csv',
 "AlainD'Amour.csv",
 'AlamgirChoudhury.csv',
 'AlanAmbrisco.csv',
 'AlanBass.csv',
 'AlanBell.csv',
 'AlanBradshaw.csv',
 'AlanBrumagim.csv',
 'AlanCavaiola.csv',
 'AlanCollard.csv',
 'AlanDavis.csv',
 'AlanDickin.csv',
 'AlanDowns.csv',
 'AlanFoster.csv',
 'AlanHyde.csv',
 'AlanJacobs.csv',
 'AlanJoseph.csv',
 'AlanKaminsky.csv',
 'AlanMcGee.csv',
 'AlanMitchell.csv',
 'AlanOverstreet.csv',
 'AlanRosenbaum.csv',
 'AlanSchiller.csv',
 'AlanSheffield.csv',
 'AlanStreett.csv',
 'AlbertLam.csv',
 'AlbertMastromartino.csv',
 'AlbertPage.csv',
 'AlbertPyzik.csv',
 'AlbertSimon.csv',
 'AlbertWidman.csv',
 'AlbinCofone.csv',
 'AlCarroll.csv',
 'AleciaBoruta-Sadkowski.csv',
 'AlecSchramm.csv',
 'AlejandraBronfman.csv',
 'Alex M.Saragoza.csv',
 'AlexanderGaeta.csv',
 'AlexanderPavuk.csv',
 'AlexandraJuhasz.csv',
 'AlexandreAvdulov.csv',
 'AlexandrosKyrou.csv',
 'AlexBielajew.csv',
 'AlexeiKaltchenko.csv',
 'AlexIosevich.csv',
 'AlexKasman.csv',
 'AlexNava.csv',
 'AlexNaylor.csv',
 'AlexPanayides.csv',
 'AlexPurugganan.csv',
 'AlexSevilla.csv',
 'AlexThompson.csv',
 'AlfredAkinsete.csv',
 'AlfredChan.csv',
 'AlfredoAlvarez.csv',
 'AlfredoPerez-Davila.csv',
 'AlfredPrettyman.csv',
 'AlfredTaylor.csv',
 'AlfriedSchulte-Bockholt.csv',
 'AliceLarue.csv',
 'AliceMarciel.csv',
 'AliceNewman.csv',
 'AliceQuiocho.csv',
 'AliceRoutely.csv',
 'AliciaMartinez-Marco.csv',
 'AliMir.csv',
 'AliSedaghat.csv',
 'AliSefrioui.csv',
 'AliShoja.csv',
 'AlisonCaplan.csv',
 'AlisonShonkwiler.csv',
 'AllaLos.csv',
 'AllanWolper.csv',
 'AllanZollman.csv',
 'AllardJongman.csv',
 'AllenAldridge.csv',
 'AllenCrocket.csv',
 'AllenHamlin.csv',
 'AllenLockyer.csv',
 'AllenSchaefer.csv',
 'AllenScult.csv',
 'AllenSherwin.csv',
 'AllisonBurdette.csv',
 'AllisonCamelot.csv',
 'AllisonCleveland.csv',
 'AllisonCooke.csv',
 'AllisonDo.csv',
 'AllisonHepler.csv',
 'AllysiaGidaszewski.csv',
 'AlokBerry.csv',
 'AlonzoGaskill.csv',
 'AlPilant.csv',
 'AlRosenbloom.csv',
 'AlTrujillo.csv',
 'AlvinSnadowsky.csv',
 'AlWerner.csv',
 'AlysonMitchell.csv',
 'AmadouGaye.csv',
 'AmaliaMondriguez.csv',
 'AMarotta.csv',
 'AmbikaBhargava.csv',
 'AmerjitChadda.csv',
 'AmieMcKibban.csv',
 'AminIbrahim.csv',
 'AMinor.csv',
 'AmirHassanpour.csv',
 'AmirMarvasti.csv',
 'AmitLath.csv',
 'AmorJnifene.csv',
 'AmparoHernandez-Folch.csv',
 'AmyAzul.csv',
 'AmyCampbell.csv',
 'AmyDoering.csv',
 'AmyFrazier.csv',
 'AmyHilden.csv',
 'AmyKoning.csv',
 'AmyNewman.csv',
 'AmyNovak.csv',
 'AmyShelton.csv',
 'AmySun.csv',
 'AmyTrogan.csv',
 'Ana MariaMyers.csv',
 'AnaAlmonte.csv',
 'AnaDias.csv',
 'AnaHorton.csv',
 'AnantaAlva.csv',
 'AnanyaMukherjee Reed.csv',
 'AnaRamos-Zayas.csv',
 'AnatolyKuklov.csv',
 'AncaMustata.csv',
 'AnderMonson.csv',
 'AndrasGordon.csv',
 'AndreaBell.csv',
 'AndreaGarzoni.csv',
 'AndreaGiampetro-Meyer.csv',
 'AndreaJolley.csv',
 'AndreaKleimola.csv',
 'AndreaLeslie.csv',
 'AndreaLucas-Krauss.csv',
 'AndreaMillette.csv',
 'AndreaMorgan.csv',
 "AndreaO'Bryan.csv",
 'AndreasBaur.csv',
 'AndreaSimpkins.csv',
 'AndreaSteiner.csv',
 'AndreaUrice.csv',
 'AndreaWells.csv',
 'AndreaWoody.csv',
 'AndreGreer.csv',
 'AndreiSimic.csv',
 'AndreiStanishevsky.csv',
 'AndrewAisenberg.csv',
 'AndrewBarnes.csv',
 'AndrewBarros.csv',
 'AndrewBell.csv',
 'AndrewBergerson.csv',
 'AndrewDelamater.csv',
 'AndrewDevitt.csv',
 'AndrewDrozd.csv',
 'AndrewGlennon.csv',
 'AndrewIrvine.csv',
 'AndrewLee.csv',
 'AndrewLesk.csv',
 'AndrewLo.csv',
 'AndrewMason.csv',
 'AndrewMcKintosh.csv',
 'AndrewMcWilliams.csv',
 'AndrewMorehead.csv',
 'AndrewNyaboga.csv',
 'AndrewParr.csv',
 'AndrewPerry.csv',
 'AndrewRobinson.csv',
 'AndrewRobson.csv',
 'AndrewTedford.csv',
 'AndrewTomko.csv',
 'AndrewWaterhouse.csv',
 'AndrewYoung.csv',
 'AndrzejCzajkowski.csv',
 'AndyAnderson.csv',
 'AndyChiles.csv',
 'AndyFlynn.csv',
 'AndyJohnson.csv',
 'AndyJones.csv',
 'AndyKatz.csv',
 'AndyLozowski.csv',
 'AndyPomerantz.csv',
 'AndyRothman.csv',
 'AndySchott.csv',
 'AndyTerry.csv',
 'AndyTufano.csv',
 'AngelaBartoli.csv',
 'AngelaMartino.csv',
 "AngelaO'Mahony.csv",
 'AngelaSchwer.csv',
 'AngelesSerrano-Ripoll.csv',
 'AngelGutierrez.csv',
 'AngelicaVessella.csv',
 'AngeloMastromonaco.csv',
 'AngieChabram-Dernersesian.csv',
 'AngieFord.csv',
 'AngusWoodward.csv',
 'AniAharonian.csv',
 'AniketBhattacharya.csv',
 'AnitaAikman.csv',
 'AnitaGirton.csv',
 'AnitaHooper.csv',
 'AnitaMeehan.csv',
 'AnitaSharm.csv',
 'AnnaCox.csv',
 'AnnAllen.csv',
 'AnnaSaroli.csv',
 'AnnaTilberg.csv',
 'AnnBartolo.csv',
 'AnnBastianelli.csv',
 'AnnClark.csv',
 'AnnDavis.csv',
 'Anne L.Dearing.csv',
 'Anne MarieTamis-Nasello.csv',
 'Anne-MarieLyons.csv',
 'AnneApplin.csv',
 'AnneDrougas.csv',
 'AnneGaines.csv',
 'AnneGuerinel.csv',
 'AnneGupton.csv',
 'AnneHaarer.csv',
 'AnneJordan.csv',
 'AnneKirschmann.csv',
 'AnneKugler.csv',
 'AnneLech.csv',
 'AnneLewis.csv',
 'AnneLittle.csv',
 'AnneMacDonald.csv',
 'AnneRaine.csv',
 'AnneRamirez.csv',
 'AnnetteGuertin.csv',
 'AnnetteLeblanc.csv',
 'AnnetteSanger.csv',
 'AnnetteSisson.csv',
 'AnneTuryn.csv',
 'AnneVoth.csv',
 'AnneWall.csv',
 'AnnFellinger.csv',
 'AnnHadley.csv',
 'AnnHall.csv',
 'AnnHaugo.csv',
 'AnnieGilson.csv',
 'AnnieHickling.csv',
 'AnnisGolden.csv',
 'AnnLewald.csv',
 'AnnLyden.csv',
 'AnnMerriwether.csv',
 'AnnPabst.csv',
 'AnnPirruccello.csv',
 'AnnRasmussen.csv',
 'AnnSt. John.csv',
 'AnnSweeney.csv',
 'AnnTaylor.csv',
 'AnnVan Dijk.csv',
 'AnthonyBrickhouse.csv',
 'AnthonyCelso.csv',
 'AnthonyFortini.csv',
 'AnthonyIarrobino.csv',
 'AnthonyJames.csv',
 'AnthonyKaldellis.csv',
 'AnthonyKuroski.csv',
 'AnthonyRohack.csv',
 'AnthonyRusso.csv',
 'AnthonySquillace.csv',
 'AnthonyStewart.csv',
 'AnthonyZera.csv',
 'AntoinetteBooth.csv',
 'AntoinetteBrazouski.csv',
 'AntoinetteGeldun.csv',
 'AntoinetteManiatty.csv',
 'AntoinetteMoore.csv',
 'AntonArmstrong.csv',
 'AntonioAlfonso.csv',
 'AntonyValletta.csv',
 'AnujMubayi.csv',
 'AnuradhaBasu.csv',
 'AnuSharma.csv',
 'AnvarZakhidov.csv',
 'AnwarulHaque.csv',
 'AOsaitile.csv',
 'ApostolosParaskevas.csv',
 'AprilAllen-Materowski.csv',
 'AprilDuvic.csv',
 'AprilHaggard.csv',
 'AprilHess.csv',
 'AprilMohr.csv',
 'ArchieFaircloth.csv',
 'ArdenHopkin.csv',
 'ArdeVakilzadeh.csv',
 'ArielGrey.csv',
 'ArielSalzmann.csv',
 'ArifBabul.csv',
 'ArlanSchultz.csv',
 'ArleneGreen.csv',
 'ArleneNoble.csv',
 'ArleneYoung.csv',
 'ArmineLulejian.csv',
 'ArneKislenko.csv',
 'ArnoldKaminsky.csv',
 'AronGerhart.csv',
 'ArpiSarafian.csv',
 'Arthur W.Allaway.csv',
 'ArthurChapman.csv',
 'ArthurKroker.csv',
 "ArthurO'Sullivan.csv",
 'ArthurRaymond.csv',
 'ArthurRowe.csv',
 'ArthurTolve.csv',
 'ArthurTyson.csv',
 'ArturCzumaj.csv',
 "ArunaD'Souza.csv",
 'ArunBhardwaj.csv',
 'ArunSundararajan.csv',
 'ARuttenbur.csv',
 'AsaadAl Salman.csv',
 'AsakoNo.csv',
 'AshaVaradharajan.csv',
 'AshimDatta.csv',
 'AshleyHawkins.csv',
 'AshotDjrbashian.csv',
 'AshrafShirani.csv',
 'AsimGangopadhyaya.csv',
 'AtifWahba.csv',
 'AtiqSyed.csv',
 'AubreyLebard.csv',
 'AudreyGuskey.csv',
 'AudreyMathews.csv',
 'AugieJanner.csv',
 'AugustineArize.csv',
 'AugustineDike.csv',
 'AugustineDuru.csv',
 'AuroMukherjee.csv',
 'AuroraWallace.csv',
 'AustenClark.csv',
 'AustinGordon.csv',
 'AuYoung.csv',
 'AvaChitwood.csv',
 'AvaleeBeckman.csv',
 'AverellManes.csv',
 'AvrahamHoltz.csv',
 "AysanSev'Er.csv",
 'Ayse A.Sahin.csv',
 'AzadeSeyhan.csv',
 'AzinEnshai.csv',
 'B JShaw.csv',
 'BabatundeOgunnaike.csv',
 'BagherModjtahedi.csv',
 'BahameHoussain.csv',
 'BakhtierFarouk.csv',
 'BaneVasic.csv',
 'BarakCaine.csv',
 'BarbaraBrehm-Curtis.csv',
 'BarbaraBugg.csv',
 'BarbaraBurke.csv',
 'BarbaraCostello.csv',
 'BarbaraCzaban.csv',
 'BarbaraDavis.csv',
 'BarbaraFrank.csv',
 'BarbaraFrisken.csv',
 'BarbaraHinshaw.csv',
 'BarbaraJacquay.csv',
 'BarbaraKalvelage.csv',
 'BarbaraKimmelman.csv',
 'BarbaraKorb.csv',
 'BarbaraKren.csv',
 'BarbaraLafferty.csv',
 'BarbaraLenington.csv',
 'BarbaraMcIntyre.csv',
 "BarbaraO'Donnell.csv",
 "BarbaraO'Neal.csv",
 'BarbaraOdabashian.csv',
 'BarbaraOwen.csv',
 'BarbaraParrish.csv',
 'BarbaraPoole.csv',
 'BarbaraRatcliffe.csv',
 'BarbaraRau.csv',
 'BarbaraRostick.csv',
 'BarbaraStone.csv',
 'BarbaraStreet.csv',
 'BarbaraTannert-Smith.csv',
 'BarbaraVallaly.csv',
 'BarbaraVon Barghahn-Calvetti.csv',
 'BarbaraWhite.csv',
 'BarbCaruso.csv',
 'BarbFisher-Townsend.csv',
 'BarbMantello.csv',
 'BarinNag.csv',
 'BarretBryant.csv',
 'BarryBurns.csv',
 'BarryChernoff.csv',
 'BarryCohen.csv',
 'BarryCondron.csv',
 'BarryCroom.csv',
 'BarryCurtis.csv',
 'BarryGaines.csv',
 'BarryHall.csv',
 'BarryHicks.csv',
 'BarryHiney.csv',
 'BarryJones.csv',
 'BarryShank.csv',
 'BarrySheffield.csv',
 'BarryStroud.csv',
 'BarrySyrett.csv',
 'BarryThomas.csv',
 'BarryWood.csv',
 'BasilioMonteiro.csv',
 'BBratcher.csv',
 'BecharaAbboud.csv',
 'BeckieFlannagan.csv',
 'BeckyBenchik.csv',
 'BeckyJones.csv',
 'BeckyMcConnell.csv',
 'BeckySmith.csv',
 'BehrouzTabrizi.csv',
 'BelindaTurk.csv',
 'BelitaFaki.csv',
 'BenErlandson.csv',
 'BenHawkins.csv',
 'BenitaSampedro.csv',
 'BenjaminBahan.csv',
 'BenjaminFoster.csv',
 'BenjaminHett.csv',
 'BenjaminLiebman.csv',
 'BenjaminWoods.csv',
 'BennettBaack.csv',
 'BennetteWhitmore.csv',
 'BenNewling.csv',
 'BenniePerdue.csv',
 'BennieWaller.csv',
 'BenScachter.csv',
 'BerartPd.csv',
 'BernadetteDavis.csv',
 'BernadetteKapocias.csv',
 'BernaditaLlanos.csv',
 'BernardChapais.csv',
 'BernardCooperman.csv',
 'BernardKuhn.csv',
 'BernardLugauer.csv',
 'BernardReginster.csv',
 'BernardVerkamp.csv',
 'BernardWalker.csv',
 'BerndEstabrook.csv',
 'BernieBlumenthal.csv',
 'BernieHayes.csv',
 'BertellOllman.csv',
 'BertramGamory.csv',
 'BertramKaron.csv',
 'BertramKaufhold.csv',
 'BerylKalisa.csv',
 'BethanieFrank.csv',
 'BethanyLarson.csv',
 'BethBattles.csv',
 'BethBennett.csv',
 'BethClary.csv',
 'BethCunin.csv',
 'BethErnest.csv',
 'BethFratkin.csv',
 'BethHeyart.csv',
 'BethJones.csv',
 'BethKolp.csv',
 'BethLamoureux.csv',
 'BethLevy.csv',
 'BethRiggs.csv',
 'BethSonnier.csv',
 'BethTodd.csv',
 'BethViquesney.csv',
 'BetsyGlade.csv',
 'BetteLondon.csv',
 'BettyDillon.csv',
 'BettyEnsminger.csv',
 'BettyGarrity.csv',
 'BettyHannum.csv',
 'BettyKiehl.csv',
 'BettyZacate.csv',
 'BeverlyChildress.csv',
 'BeverlyGaddy.csv',
 'BeverlyLee.csv',
 'BeverlyMatthews.csv',
 'BillAllen.csv',
 'BillBarber.csv',
 'BillBarrett.csv',
 'BillBoon.csv',
 'BillBorda.csv',
 'BillEarls.csv',
 'BillEffler.csv',
 'BillHartmann.csv',
 'BillHodges.csv',
 'BillHolland.csv',
 'BillieLo.csv',
 'BillMcConkey.csv',
 'BillMcGarvey.csv',
 'BillMeiers.csv',
 'BillMiller.csv',
 'BillMurphy.csv',
 'BillPeterson.csv',
 'BillPye.csv',
 'BillRamsey.csv',
 'BillSanders.csv',
 'BillSeaburg.csv',
 'BillShendow.csv',
 'BillStout.csv',
 'BillStrecker.csv',
 'BillThompson.csv',
 'BillWenthe.csv',
 'BillWhitaker.csv',
 'BillWilson.csv',
 'BillWine.csv',
 'BillWolfe.csv',
 'BillWoodward.csv',
 'BillyBohne.csv',
 'BillyDurham.csv',
 'BillZito.csv',
 'BinaPatel.csv',
 'BingwuWang.csv',
 'BinitaMehta.csv',
 'BirgitPianosi.csv',
 'BJacowitz.csv',
 'BjBenton.csv',
 'BJobe Jr..csv',
 'BlakeHobby.csv',
 'BlakeSorem.csv',
 'BobAlter.csv',
 'BobBaugher.csv',
 'BobBednar.csv',
 'BobBetts.csv',
 'BobbiRosenquest.csv',
 'BobBrady.csv',
 'BobbyCarmichael.csv',
 'BobbyDonaldson.csv',
 'BobbySolmon.csv',
 'BobCampbell.csv',
 'BobClark.csv',
 'BobClifton.csv',
 'BobDonmoyer.csv',
 'BobFilson.csv',
 'BobFulton.csv',
 'BobGillies.csv',
 'BobGlushko.csv',
 'BobHall.csv',
 'BobHalliday.csv',
 'BobHolsman.csv',
 'BobKieburtz.csv',
 'BobKittenger.csv',
 'BobKuchinsky.csv',
 'BobLanier.csv',
 'BobLebda.csv',
 'BobLombard.csv',
 'BobMilgrom.csv',
 'BobMitchell.csv',
 'BobOrso.csv',
 'BobSeidenstein.csv',
 'BobSitelman.csv',
 'BobTeti.csv',
 'BobTuttle.csv',
 'BobWalsh.csv',
 'BobWillenbrink.csv',
 'BobYolles.csv',
 'BobYoung.csv',
 'BoEckerd.csv',
 'BogdanSuceavã.csv',
 'BojanaObrenic.csv',
 'BoNalley.csv',
 'BonnieBanks.csv',
 'BonnieBlumberg.csv',
 'BonnieCummings.csv',
 'BonnieDennis.csv',
 'BonnieEarnst.csv',
 'BonnieGlass-Coffin.csv',
 'BonnieHayes.csv',
 'BonnieJohnson.csv',
 'BonniePerlstein.csv',
 'BonnieVeysey.csv',
 'BoumedieneHamzi.csv',
 'BPeterson.csv',
 'BPetri.csv',
 'BradChin.csv',
 'BradDearden.csv',
 'BradfordSt. Martin.csv',
 'BradFrazier.csv',
 'BradHann.csv',
 'BradJett.csv',
 'BradleyBielski.csv',
 'BradLovoi.csv',
 'BradyRimes.csv',
 'BradyWilliams.csv',
 'BrandieSiegfried.csv',
 'BrandyZito.csv',
 'BransonBrade.csv',
 'BrantAdams.csv',
 'BrendaAdams.csv',
 'BrendaDouglas.csv',
 'BrendaHawker.csv',
 'BrendaMelendy.csv',
 'BrendaMitchell.csv',
 'BrendaMoore.csv',
 'BrendanQuine.csv',
 'BrendaWolfer.csv',
 'BrendonSwedlow.csv',
 'BrennaBetcher.csv',
 'BrenndaYoung.csv',
 'BrentMacDonald.csv',
 'BrentNielsen.csv',
 'BretBenjamin.csv',
 'BretMcMurran.csv',
 'BrettBlake.csv',
 'BrettLong.csv',
 'BrettTjaden.csv',
 'BrianAnderson.csv',
 'BrianBay.csv',
 'BrianBradford.csv',
 'BrianBridson.csv',
 'BrianCook.csv',
 'BrianDempster.csv',
 'BrianErnsting.csv',
 'BrianFloyd.csv',
 'BrianGeorge.csv',
 'BrianGilbert.csv',
 'BrianGlabb.csv',
 'BrianGobbett.csv',
 'BrianGould.csv',
 'BrianHeuett.csv',
 'BrianHiggins.csv',
 'BrianHumphrey.csv',
 'BrianKarasek.csv',
 'BrianLenzmeier.csv',
 'BrianLittlefield.csv',
 'BrianLudlow.csv',
 'BrianMacKie.csv',
 'BrianMcGuinness.csv',
 'BrianMcIlroy.csv',
 'BrianMcNelis.csv',
 'BrianNaughton.csv',
 "BrianO'Brien.csv",
 'BrianPirman.csv',
 'BrianPotter.csv',
 'BrianRose.csv',
 'BrianSauriol.csv',
 'BrianSchrader.csv',
 'BrianSherman.csv',
 'BrianStorey.csv',
 'BrianThomas.csv',
 'BrianWells.csv',
 'BrianYarnall.csv',
 'BridgetteLong.csv',
 'BrigetteMorretti-Coski.csv',
 'BrijLunine.csv',
 'BrittLeatham.csv',
 'Bro. JoeBurke.csv',
 'BrockKlein.csv',
 'BrooksMcKinney.csv',
 'BrowynConrad.csv',
 'BruceBanks.csv',
 'BruceBeck.csv',
 'BruceBennet.csv',
 'BruceBennett.csv',
 'BruceBlaylock.csv',
 'BruceBoliver.csv',
 'BruceCooper.csv',
 'BruceFreeborn.csv',
 'BruceHammond.csv',
 'BruceHicks.csv',
 'BruceHoover.csv',
 'BruceJanacek.csv',
 'BruceLenore.csv',
 'BruceMacMurray.csv',
 'BruceMartin.csv',
 'BruceNormandia.csv',
 'BrucePeckham.csv',
 'BrucePeterson.csv',
 'BrucePortscheller.csv',
 'BruceSun.csv',
 'BruceTyler.csv',
 'BruceUnderhill.csv',
 'BruceWatson.csv',
 'BrunellaWindsor.csv',
 'BrunoKappes.csv',
 'BryanEldredge.csv',
 'BryanFair.csv',
 'BryanFisher.csv',
 'BryanHanks.csv',
 'BryanMan.csv',
 "BryanO'Neal.csv",
 'BryanWhaley.csv',
 'BrynUpton.csv',
 'BryonSpecie.csv',
 'BTaylor.csv',
 'BTrentham.csv',
 'BulentUyar.csv',
 'BurkardEberlein.csv',
 'BurlonWilkerson.csv',
 'BurtonWebb.csv',
 'BurtVisotzky.csv',
 'ButchTincher.csv',
 'ButtonBrady.csv',
 'BuzzBrookman.csv',
 'BWall.csv',
 'C.Ing.csv',
 'C.McKeown.csv',
 'CafDowlah.csv',
 'CalJillson.csv',
 'CallynYorke.csv',
 'CalvinHayes.csv',
 'CalvinJenkins.csv',
 'CameronGhalambor.csv',
 'CameronMongomery.csv',
 'CameronTsujita.csv',
 'CamiloRojas.csv',
 'CamMacDonald.csv',
 'CamronAmin.csv',
 'CamSylvester.csv',
 'CandaceFavilla.csv',
 'CandaceJohnson.csv',
 'CandaceKent.csv',
 'CandiceWhite.csv',
 'CandyJustice.csv',
 'CareyBorkoski.csv',
 'CareyCarpenter.csv',
 'CareyHissey.csv',
 'Carl DwaineCochran.csv',
 'CarlaBagnoli.csv',
 'CarlaCastellaw.csv',
 'CarlaHornback.csv',
 'CarlaKirkwood.csv',
 'CarlaVerderame.csv',
 'CarlCharnetski.csv',
 'CarleyAugustine.csv',
 'CarlHuber.csv',
 'CarlJorgensen.csv',
 'CarlLeafstedt.csv',
 'CarlLibis.csv',
 'CarlMancuso.csv',
 'CarlMcFarland.csv',
 'CarlNelson.csv',
 'CarloAlfare.csv',
 'CarloFilice.csv',
 'CarlosAlsua.csv',
 'CarlosArauz.csv',
 'CarlosCenteno.csv',
 'CarlosDiazcobo.csv',
 'CarlosGuerra.csv',
 'CarlosLebron.csv',
 'CarlosMujal.csv',
 'CarlosSimmerling.csv',
 'CarlosValiente.csv',
 'CarlPratt.csv',
 'CarmenAntommarchi.csv',
 'CarmenAvila.csv',
 'CarmenBrowne.csv',
 'CarmenFaccini.csv',
 'CarmenHerman.csv',
 'CarmenKlohe.csv',
 'CarmenNiessen.csv',
 'CarmenWittmeier.csv',
 'CarmineDecarlo.csv',
 'CarmineMorelli.csv',
 'CarneyMatheson.csv',
 'Carol AnnDavis.csv',
 'CarolAylward.csv',
 'CarolBarnes.csv',
 'CarolBennet.csv',
 'CarolBinkerd.csv',
 'CarolBuser.csv',
 'CarolDuncan.csv',
 'CaroleCasten.csv',
 'CaroleMyscofski.csv',
 'CarolePatterson.csv',
 'CaroleWaterhouse.csv',
 'CarolFenn.csv',
 'CarolFrishberg.csv',
 'CarolGray.csv',
 'CarolHayward.csv',
 'CarolineHong.csv',
 'CarolineHunt.csv',
 'CarolineSchacht.csv',
 'CarolJaeger.csv',
 'CarolMacAll.csv',
 'CarolMartin.csv',
 'CarolOehlbeck.csv',
 'CarolOsborne.csv',
 'CarolPasternak.csv',
 'CarolPhillippe.csv',
 'CarolPynchon.csv',
 'CarolRowey.csv',
 'CarolSerotta.csv',
 'CarolSolon.csv',
 'CarolStrandberg.csv',
 'CarolStrauss-Sotiropoulos.csv',
 'CarolTopping.csv',
 'CarolTurner.csv',
 'CarolWicks.csv',
 'CarolynByrd.csv',
 'CarolynDetmer.csv',
 'CarolynDirksen.csv',
 'CarolynFerrell.csv',
 'CarolynHolcroft.csv',
 'CarolynIves.csv',
 'CarolynKeen.csv',
 'CarolynKrause.csv',
 'CarolynLesjak.csv',
 'CarolynMacTavish.csv',
 'CarolynMalone.csv',
 'CarolynMorse.csv',
 'CarolynPerry.csv',
 'CarrieGordon.csv',
 'CarrieKing.csv',
 'CarrieMenendez.csv',
 'Carroll LesRamos.csv',
 'CarrollHale.csv',
 'CarylClark.csv',
 'CarynBabaian.csv',
 'CaryWard.csv',
 'CathaPaquette.csv',
 'CatherineChen.csv',
 'CatherineCiepiela.csv',
 'CatherineDollard.csv',
 'CatherineEllis.csv',
 'CatherineGriffiths.csv',
 'CatherineMartin.csv',
 'CatherineMcClenahan.csv',
 'CatherineMcKeen.csv',
 'CatherinePloye.csv',
 'CatherineWiley.csv',
 'CatherineWright.csv',
 'CatheyCostin.csv',
 'CathieKorobey.csv',
 'CathyBrostrand.csv',
 'CathyFleischer.csv',
 'CathyFraley.csv',
 'CathyFrierson.csv',
 'CathyFrost.csv',
 'CathyHesse.csv',
 'CathyRogers.csv',
 'CathyVelez.csv',
 'CathyZemlick.csv',
 'CattiJames.csv',
 'CBeals.csv',
 'CConrad.csv',
 'CeceliaTichi.csv',
 'CecileCharlebois.csv',
 'CeciliaCloughly.csv',
 'CeciliaMiller.csv',
 'CelesteHumphrey.csv',
 'CeliaApplegate.csv',
 'CeliaRabinovitch.csv',
 'CeliaSgroi.csv',
 'CelsoBatalha.csv',
 'ChadStebbins.csv',
 'ChalBenson.csv',
 'ChampakPanchal.csv',
 'CHampton.csv',
 'ChangfengChen.csv',
 'Chao-ChihHuang.csv',
 'CharisseWillis.csv',
 'CharleneKinsey.csv',
 'CharleneMusgrove.csv',
 'Charles (Chuck)Walker.csv',
 'Charles A.Fiore.csv',
 'Charles F.Amelin.csv',
 'CharlesAckerson.csv',

In [3]:
path = './PycharmProjects/rateMyProf/'
df = pd.read_csv(path + filenames[0]).iloc[:, 1:]

for i in range(1, len(filenames)):
    df_temp = pd.read_csv(path + filenames[i]).iloc[:, 1:]
    df = pd.concat([df, df_temp], ignore_index=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141729 entries, 0 to 141728
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Name                141729 non-null  object
 1   OverallRate         141729 non-null  float64
 2   TakeAgain           91066 non-null   object
 3   Overall_Difficulty  141729 non-null  float64
 4   Tags                103375 non-null  object
 5   Emotion             108965 non-null  object
 6   QualityRate         108965 non-null  float64
 7   StudentDifficulty   108965 non-null  float64
 8   Background          141729 non-null  object
 9   Comment             108809 non-null  object
 10  CommentTags         141729 non-null  object
dtypes: float64(4), object(7)
memory usage: 11.9+ MB

In [5]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68880 entries, 237 to 141728
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                68880 non-null  object
 1   OverallRate         68880 non-null  float64
 2   TakeAgain           68880 non-null  object
 3   Overall_Difficulty  68880 non-null  float64
 4   Tags                68880 non-null  object
 5   Emotion             68880 non-null  object
 6   QualityRate         68880 non-null  float64
 7   StudentDifficulty   68880 non-null  float64
 8   Background          68880 non-null  object
 9   Comment             68880 non-null  object
 10  CommentTags         68880 non-null  object
dtypes: float64(4), object(7)
memory usage: 6.3+ MB

In [6]:
df = df.reset_index().drop(['index'], axis = 1)
df.head()

,Name,OverallRate,TakeAgain,Overall_Difficulty,Tags,Emotion,QualityRate,StudentDifficulty,Background,Comment,CommentTags
0,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,2.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",The class was very intimidating at first. Howe...,"['Get ready to read', 'Clear grading criteria']"
1,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,1.0,5.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",I have never rated a professor before because ...,"[' ', '1', ' ', '0']"
2,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,1.0,5.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",A teacher I would never take again. She is not...,"[' ', '1', ' ', '0']"
3,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,1.0,4.0,"['Attendance', ': ', 'Mandatory', 'Grade', ': ...",Honestly. I have never once taken the time to ...,"[' ', '1', ' ', '0']"
4,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,1.0,5.0,"['Attendance', ': ', 'Mandatory', 'Grade', ': ...",This woman is awful. She can't teach for anyth...,"[' ', '1', ' ', '0']"

In [7]:
df.to_csv('Uncleaned_sample.csv', index=False)

### CommentTags

In [8]:
import re

def digit_filter(text):
    result = re.findall('[0-9]+', text)
    if result == []:
        return False
    else:
        return result

In [9]:
comTags = df['CommentTags']

comDigit = comTags[comTags.apply(digit_filter) != False]
comDigit

1        [' ', '1', ' ', '0']
2        [' ', '1', ' ', '0']
3        [' ', '1', ' ', '0']
4        [' ', '1', ' ', '0']
5        [' ', '1', ' ', '0']
                 ...
68874    [' ', '0', ' ', '0']
68876    [' ', '2', ' ', '0']
68877    [' ', '1', ' ', '1']
68878    [' ', '2', ' ', '0']
68879    [' ', '0', ' ', '1']
Name: CommentTags, Length: 42038, dtype: object

#### Drop Non-String Tags

In [10]:
index_list = comDigit.index.to_list()

In [11]:
df = df.drop(index = index_list)
df = df.reset_index().drop(['index'], axis = 1)
df.head()

,Name,OverallRate,TakeAgain,Overall_Difficulty,Tags,Emotion,QualityRate,StudentDifficulty,Background,Comment,CommentTags
0,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,2.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",The class was very intimidating at first. Howe...,"['Get ready to read', 'Clear grading criteria']"
1,.Giordani,4.1,100%,2.8,"['Beware of pop quizzes', 'Tough grader', 'Get...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",Amazing woman. I wish every professor was like...,"['Participation matters', 'Inspirational', 'Ca..."
2,.Heimgartner,4.2,100%,1.6,"['Amazing lectures ', 'Clear grading criteria'...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",He was a great teacher and well respected by m...,"['Respected', 'Clear grading criteria', 'Amazi..."
3,.Huey,3.8,50%,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awful,1.0,5.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",I had to retake Biology and drop out of his cl...,"['Tough Grader', 'TEST HEAVY', 'LECTURE HEAVY']"
4,.Huey,3.8,50%,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awesome,5.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Best teacher that I have ever had. You will le...,['Respected']

In [12]:
df.to_csv('Raw_datda.csv', index=False)

### Clean Student `CommentTags`

In [13]:
comTags = df['CommentTags']
comTags

0          ['Get ready to read', 'Clear grading criteria']
1        ['Participation matters', 'Inspirational', 'Ca...
2        ['Respected', 'Clear grading criteria', 'Amazi...
3          ['Tough Grader', 'TEST HEAVY', 'LECTURE HEAVY']
4                                            ['Respected']
                               ...
26837           ['Graded by few things', 'Group projects']
26838    ['Get ready to read', 'Clear grading criteria'...
26839                                           ['Caring']
26840    ['Gives good feedback', 'Clear grading criteri...
26841    ['Participation matters', "Skip class? You won...
Name: CommentTags, Length: 26842, dtype: object

In [14]:
from string import punctuation

def remove_punctuation(document):
    keep_comma = punctuation.replace(',', '')
    no_punct = ''.join([character for character in document if character not in keep_comma])
    
    return no_punct

#### Remove punctuation, but keep comma for further separation

In [15]:
comTags_no_punct = comTags.apply(remove_punctuation)
comTags_no_punct

0                Get ready to read, Clear grading criteria
1             Participation matters, Inspirational, Caring
2        Respected, Clear grading criteria, Amazing lec...
3                  Tough Grader, TEST HEAVY, LECTURE HEAVY
4                                                Respected
                               ...
26837                 Graded by few things, Group projects
26838    Get ready to read, Clear grading criteria, Caring
26839                                               Caring
26840    Gives good feedback, Clear grading criteria, C...
26841    Participation matters, Skip class You wont pas...
Name: CommentTags, Length: 26842, dtype: object

#### Lowercase

In [16]:
comTags_lower = comTags_no_punct.apply(str.lower)
comTags_lower

0                get ready to read, clear grading criteria
1             participation matters, inspirational, caring
2        respected, clear grading criteria, amazing lec...
3                  tough grader, test heavy, lecture heavy
4                                                respected
                               ...
26837                 graded by few things, group projects
26838    get ready to read, clear grading criteria, caring
26839                                               caring
26840    gives good feedback, clear grading criteria, c...
26841    participation matters, skip class you wont pas...
Name: CommentTags, Length: 26842, dtype: object

#### Turn combined string into separate feature tags

In [17]:
def process_tag(tags):
    tags_list = tags.split(',')
    cleaned_tags = []
    
    for item in tags_list:
        item = item.strip()
        item = item.replace(' ', '_')
        cleaned_tags.append(item)
    
    return cleaned_tags

In [18]:
comTags_cleaned = comTags_lower.apply(process_tag)
comTags_cleaned

0              [get_ready_to_read, clear_grading_criteria]
1           [participation_matters, inspirational, caring]
2        [respected, clear_grading_criteria, amazing_le...
3                [tough_grader, test_heavy, lecture_heavy]
4                                              [respected]
                               ...
26837               [graded_by_few_things, group_projects]
26838    [get_ready_to_read, clear_grading_criteria, ca...
26839                                             [caring]
26840    [gives_good_feedback, clear_grading_criteria, ...
26841    [participation_matters, skip_class_you_wont_pa...
Name: CommentTags, Length: 26842, dtype: object

In [20]:
tag_set = set([])
for index, text_list in comTags_cleaned.items():
    tag_set.update(text_list)

In [21]:
tag_set

{'accessible_outside_class',
 'amazing_lectures',
 'beware_of_pop_quizzes',
 'cares_about_students',
 'caring',
 'clear_grading_criteria',
 'extra_credit',
 'extra_credit_offered',
 'get_ready_to_read',
 'gives_good_feedback',
 'graded_by_few_things',
 'group_projects',
 'hilarious',
 'inspirational',
 'lecture_heavy',
 'lots_of_homework',
 'online_savvy',
 'participation_matters',
 'respected',
 'respected_by_students',
 'skip_class_you_wont_pass',
 'so_many_papers',
 'test_heavy',
 'tests_are_tough',
 'tests_not_many',
 'tough_grader',
 'would_take_again'}

In [22]:
len(tag_set)

27

In [23]:
tag_df = pd.DataFrame(columns = tag_set)
tag_df = tag_df.sort_index(axis = 1)
tag_df

Empty DataFrame
Columns: [accessible_outside_class, amazing_lectures, beware_of_pop_quizzes, cares_about_students, caring, clear_grading_criteria, extra_credit, extra_credit_offered, get_ready_to_read, gives_good_feedback, graded_by_few_things, group_projects, hilarious, inspirational, lecture_heavy, lots_of_homework, online_savvy, participation_matters, respected, respected_by_students, skip_class_you_wont_pass, so_many_papers, test_heavy, tests_are_tough, tests_not_many, tough_grader, would_take_again]
Index: []

[0 rows x 27 columns]

In [24]:
tag_data = np.zeros((len(comTags_cleaned), len(tag_set)))

for index, tag_list in comTags_cleaned.items():
    for tag in tag_list:
        if tag in list(tag_df.columns):
            col_index = list(tag_df.columns).index(tag)
            tag_data[index, col_index] = 1

In [25]:
tag_encode = pd.DataFrame(tag_data, columns = tag_df.columns, dtype='int32')
tag_encode

,accessible_outside_class,amazing_lectures,beware_of_pop_quizzes,cares_about_students,caring,clear_grading_criteria,extra_credit,extra_credit_offered,get_ready_to_read,gives_good_feedback,...,participation_matters,respected,respected_by_students,skip_class_you_wont_pass,so_many_papers,test_heavy,tests_are_tough,tests_not_many,tough_grader,would_take_again
0,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,0,0,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26839,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26840,0,0,0,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26841,0,1,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

#### Combine similar meaning attributes

In [26]:
tag_encode['caring'] = tag_encode['caring'] + tag_encode['cares_about_students']
tag_encode['extra_credit'] = tag_encode['extra_credit'] + tag_encode['extra_credit_offered']
tag_encode['respected'] = tag_encode['respected'] + tag_encode['respected_by_students']

In [27]:
tag_encode = tag_encode.drop(['cares_about_students', 'extra_credit_offered', 'respected_by_students'], axis = 1)

#### We can consider filter some uncommonly seen evaluation tags

In [28]:
tag_encode.sum().sort_values()

online_savvy                  57
tests_not_many                87
tests_are_tough              190
would_take_again             235
beware_of_pop_quizzes        770
so_many_papers              1183
group_projects              1246
extra_credit                1758
inspirational               2574
hilarious                   3190
graded_by_few_things        3240
accessible_outside_class    3370
test_heavy                  3432
clear_grading_criteria      3532
amazing_lectures            3765
participation_matters       4004
lots_of_homework            4258
lecture_heavy               4546
respected                   4709
skip_class_you_wont_pass    5018
caring                      5117
get_ready_to_read           5271
gives_good_feedback         5322
tough_grader                6319
dtype: int64

In [29]:
tag_encode = tag_encode.drop(['online_savvy', 'would_take_again', 'tests_not_many', 'tests_are_tough'], axis = 1)

In [30]:
tag_encode.sum().sort_values()

beware_of_pop_quizzes        770
so_many_papers              1183
group_projects              1246
extra_credit                1758
inspirational               2574
hilarious                   3190
graded_by_few_things        3240
accessible_outside_class    3370
test_heavy                  3432
clear_grading_criteria      3532
amazing_lectures            3765
participation_matters       4004
lots_of_homework            4258
lecture_heavy               4546
respected                   4709
skip_class_you_wont_pass    5018
caring                      5117
get_ready_to_read           5271
gives_good_feedback         5322
tough_grader                6319
dtype: int64

#### Ensure this is still a valid one-hot encoding, i.e. only 0/1 values

In [31]:
tag_encode.max()

accessible_outside_class    1
amazing_lectures            1
beware_of_pop_quizzes       1
caring                      1
clear_grading_criteria      1
extra_credit                1
get_ready_to_read           1
gives_good_feedback         1
graded_by_few_things        1
group_projects              1
hilarious                   1
inspirational               1
lecture_heavy               1
lots_of_homework            1
participation_matters       1
respected                   1
skip_class_you_wont_pass    1
so_many_papers              1
test_heavy                  1
tough_grader                1
dtype: int32

In [32]:
df_new = pd.concat([df, tag_encode], axis = 1)
df_new = df_new.drop(['CommentTags'], axis = 1)
df_new

,Name,OverallRate,TakeAgain,Overall_Difficulty,Tags,Emotion,QualityRate,StudentDifficulty,Background,Comment,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,.Garcia,1.3,0%,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,2.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",The class was very intimidating at first. Howe...,...,0,0,0,0,0,0,0,0,0,0
1,.Giordani,4.1,100%,2.8,"['Beware of pop quizzes', 'Tough grader', 'Get...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",Amazing woman. I wish every professor was like...,...,0,1,0,0,1,0,0,0,0,0
2,.Heimgartner,4.2,100%,1.6,"['Amazing lectures ', 'Clear grading criteria'...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",He was a great teacher and well respected by m...,...,0,0,0,0,0,1,0,0,0,0
3,.Huey,3.8,50%,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awful,1.0,5.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",I had to retake Biology and drop out of his cl...,...,0,0,1,0,0,0,0,0,1,1
4,.Huey,3.8,50%,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awesome,5.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Best teacher that I have ever had. You will le...,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,ZoilaMendoza,3.3,75%,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",average,3.0,2.0,"['Attendance', ': ', 'Mandatory', 'Would Take ...",She's cool. Kinda like a mom! Took her for the...,...,0,0,0,0,0,0,0,0,0,0
26838,ZoilaMendoza,3.3,75%,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...","It's honestly just a pretty easy class, it's m...",...,0,0,0,0,0,0,0,0,0,0
26839,ZoilaMendoza,3.3,75%,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,2.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...","she's really nice and understanding, and she's...",...,0,0,0,0,0,0,0,0,0,0
26840,ZoilaMendoza,3.3,75%,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Honestly one of the nicest professors you will...,...,0,0,0,0,0,0,0,0,0,0
26841,ZongDai,2.5,100%,1.6,"['Participation matters', ""Skip class? You won...",awesome,4.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Be prepared for group work. A lot of people fe...,...,0,0,0,0,1,0,1,0,0,0

### TakeAgain

- turn percentage string into float number

In [33]:
takeAgain = df['TakeAgain']

takeAgain = takeAgain.apply(lambda percent_str: percent_str.split('%')[0]).astype('float64') / 100
takeAgain

0        0.00
1        1.00
2        1.00
3        0.50
4        0.50
         ...
26837    0.75
26838    0.75
26839    0.75
26840    0.75
26841    1.00
Name: TakeAgain, Length: 26842, dtype: float64

In [34]:
takeAgain[takeAgain > 0.7]

1        1.00
2        1.00
5        1.00
7        1.00
8        1.00
         ...
26837    0.75
26838    0.75
26839    0.75
26840    0.75
26841    1.00
Name: TakeAgain, Length: 13325, dtype: float64

In [35]:
df_new['TakeAgain'] = takeAgain
df_new

,Name,OverallRate,TakeAgain,Overall_Difficulty,Tags,Emotion,QualityRate,StudentDifficulty,Background,Comment,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,.Garcia,1.3,0.00,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,2.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",The class was very intimidating at first. Howe...,...,0,0,0,0,0,0,0,0,0,0
1,.Giordani,4.1,1.00,2.8,"['Beware of pop quizzes', 'Tough grader', 'Get...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",Amazing woman. I wish every professor was like...,...,0,1,0,0,1,0,0,0,0,0
2,.Heimgartner,4.2,1.00,1.6,"['Amazing lectures ', 'Clear grading criteria'...",awesome,5.0,3.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",He was a great teacher and well respected by m...,...,0,0,0,0,0,1,0,0,0,0
3,.Huey,3.8,0.50,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awful,1.0,5.0,"['For Credit', ': ', 'Yes', 'Would Take Again'...",I had to retake Biology and drop out of his cl...,...,0,0,1,0,0,0,0,0,1,1
4,.Huey,3.8,0.50,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awesome,5.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Best teacher that I have ever had. You will le...,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",average,3.0,2.0,"['Attendance', ': ', 'Mandatory', 'Would Take ...",She's cool. Kinda like a mom! Took her for the...,...,0,0,0,0,0,0,0,0,0,0
26838,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...","It's honestly just a pretty easy class, it's m...",...,0,0,0,0,0,0,0,0,0,0
26839,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,2.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...","she's really nice and understanding, and she's...",...,0,0,0,0,0,0,0,0,0,0
26840,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Honestly one of the nicest professors you will...,...,0,0,0,0,0,0,0,0,0,0
26841,ZongDai,2.5,1.00,1.6,"['Participation matters', ""Skip class? You won...",awesome,4.0,4.0,"['For Credit', ': ', 'Yes', 'Attendance', ': '...",Be prepared for group work. A lot of people fe...,...,0,0,0,0,1,0,1,0,0,0

### Numeric Attributes
- Change string-type attributes to float numbers

In [36]:
numeric = df.loc[:, ['OverallRate', 'Overall_Difficulty', 'QualityRate', 'StudentDifficulty']]
numeric = numeric.astype('float64')
numeric.info()
numeric

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26842 entries, 0 to 26841
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OverallRate         26842 non-null  float64
 1   Overall_Difficulty  26842 non-null  float64
 2   QualityRate         26842 non-null  float64
 3   StudentDifficulty   26842 non-null  float64
dtypes: float64(4)
memory usage: 838.9 KB

       OverallRate  Overall_Difficulty  QualityRate  StudentDifficulty
0              1.3                 4.2          2.0                4.0
1              4.1                 2.8          5.0                3.0
2              4.2                 1.6          5.0                3.0
3              3.8                 3.1          1.0                5.0
4              3.8                 3.1          5.0                4.0
...            ...                 ...          ...                ...
26837          3.3                 2.7          3.0                2.0
26838          3.3                 2.7          5.0                1.0
26839          3.3                 2.7          5.0                2.0
26840          3.3                 2.7          5.0                1.0
26841          2.5                 1.6          4.0                4.0

[26842 rows x 4 columns]

In [37]:
df_new['OverallRate'] = numeric['OverallRate']
df_new['Overall_Difficulty'] = numeric['Overall_Difficulty']
df_new['QualityRate'] = numeric['QualityRate']
df_new['StudentDifficulty'] = numeric['StudentDifficulty']

In [38]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26842 entries, 0 to 26841
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      26842 non-null  object
 1   OverallRate               26842 non-null  float64
 2   TakeAgain                 26842 non-null  float64
 3   Overall_Difficulty        26842 non-null  float64
 4   Tags                      26842 non-null  object
 5   Emotion                   26842 non-null  object
 6   QualityRate               26842 non-null  float64
 7   StudentDifficulty         26842 non-null  float64
 8   Background                26842 non-null  object
 9   Comment                   26842 non-null  object
 10  accessible_outside_class  26842 non-null  int32
 11  amazing_lectures          26842 non-null  int32
 12  beware_of_pop_quizzes     26842 non-null  int32
 13  caring                    26842 non-null  int32
 14  clear_grading_criteria    26842 non-null  int32
 15  extra_credit              26842 non-null  int32
 16  get_ready_to_read         26842 non-null  int32
 17  gives_good_feedback       26842 non-null  int32
 18  graded_by_few_things      26842 non-null  int32
 19  group_projects            26842 non-null  int32
 20  hilarious                 26842 non-null  int32
 21  inspirational             26842 non-null  int32
 22  lecture_heavy             26842 non-null  int32
 23  lots_of_homework          26842 non-null  int32
 24  participation_matters     26842 non-null  int32
 25  respected                 26842 non-null  int32
 26  skip_class_you_wont_pass  26842 non-null  int32
 27  so_many_papers            26842 non-null  int32
 28  test_heavy                26842 non-null  int32
 29  tough_grader              26842 non-null  int32
dtypes: float64(5), int32(20), object(5)
memory usage: 4.1+ MB

### Emotion

In [39]:
emotion = df['Emotion']
emotion

0          awful
1        awesome
2        awesome
3          awful
4        awesome
          ...
26837    average
26838    awesome
26839    awesome
26840    awesome
26841    awesome
Name: Emotion, Length: 26842, dtype: object

In [40]:
set(emotion.tolist())

{'average', 'awesome', 'awful'}

### Comment

In [41]:
comment = df['Comment']
comment

0        The class was very intimidating at first. Howe...
1        Amazing woman. I wish every professor was like...
2        He was a great teacher and well respected by m...
3        I had to retake Biology and drop out of his cl...
4        Best teacher that I have ever had. You will le...
                               ...
26837    She's cool. Kinda like a mom! Took her for the...
26838    It's honestly just a pretty easy class, it's m...
26839    she's really nice and understanding, and she's...
26840    Honestly one of the nicest professors you will...
26841    Be prepared for group work. A lot of people fe...
Name: Comment, Length: 26842, dtype: object

In [42]:
comment[0]

'The class was very intimidating at first. However, I  ended up really enjoying the class. She allowed students to redo projects and homework for more points. The tests are almost all definitions. Memorize all of the definitions and some facts about them and you will do well. Taking this class in the spring was a great way to gain 4 more credits.'

### Background

- Treat `Missing` as one explicit category

In [43]:
bg = df_new['Background']
bg

0        ['For Credit', ': ', 'Yes', 'Attendance', ': '...
1        ['For Credit', ': ', 'Yes', 'Would Take Again'...
2        ['For Credit', ': ', 'Yes', 'Attendance', ': '...
3        ['For Credit', ': ', 'Yes', 'Would Take Again'...
4        ['For Credit', ': ', 'Yes', 'Attendance', ': '...
                               ...
26837    ['Attendance', ': ', 'Mandatory', 'Would Take ...
26838    ['For Credit', ': ', 'Yes', 'Attendance', ': '...
26839    ['For Credit', ': ', 'Yes', 'Attendance', ': '...
26840    ['For Credit', ': ', 'Yes', 'Attendance', ': '...
26841    ['For Credit', ': ', 'Yes', 'Attendance', ': '...
Name: Background, Length: 26842, dtype: object

In [44]:
from itertools import repeat

def creteria_split(bg):
    criteria = ['Credit', 'Attendance', 'Again', 'Grade', 'Textbook']
    one_hot = list(repeat('Missing', 5))
    
    # first choose non-element
    text_list = re.findall('[a-zA-Z]+', bg)
    if text_list == []:
        return one_hot

    for item in text_list:
        if item in criteria:
            index = criteria.index(item)
            content_index = text_list.index(item) + 1
            one_hot[index] = text_list[content_index]

    return one_hot

In [45]:
bg = bg.apply(creteria_split)
bg

0              [Yes, Mandatory, No, A, Yes]
1         [Yes, Missing, Yes, Missing, Yes]
2             [Yes, Mandatory, Yes, C, Yes]
3             [Yes, Missing, No, Drop, Yes]
4                   [Yes, Not, Yes, A, Yes]
                        ...
26837       [Missing, Mandatory, No, A, No]
26838        [Yes, Mandatory, Yes, Not, No]
26839          [Yes, Mandatory, Yes, A, No]
26840    [Yes, Mandatory, Yes, Missing, No]
26841         [Yes, Mandatory, Yes, B, Yes]
Name: Background, Length: 26842, dtype: object

In [47]:
Credit_list = []
Atten_list = []
Again_list = []
Grade_list = []
Textbook_list = []

for index, creteria in bg.items():
    Credit_list.append(creteria[0])
    Atten_list.append(creteria[1])
    Again_list.append(creteria[2])
    Grade_list.append(creteria[3])
    Textbook_list.append(creteria[4])

bg_filtered = pd.DataFrame({'Credit': Credit_list,
                           "Attendance": Atten_list,
                           "Student_TakeAgain": Again_list,
                           "Grade": Grade_list,
                           "Textbook": Textbook_list})

In [48]:
bg_filtered

        Credit Attendance Student_TakeAgain    Grade Textbook
0          Yes  Mandatory                No        A      Yes
1          Yes    Missing               Yes  Missing      Yes
2          Yes  Mandatory               Yes        C      Yes
3          Yes    Missing                No     Drop      Yes
4          Yes        Not               Yes        A      Yes
...        ...        ...               ...      ...      ...
26837  Missing  Mandatory                No        A       No
26838      Yes  Mandatory               Yes      Not       No
26839      Yes  Mandatory               Yes        A       No
26840      Yes  Mandatory               Yes  Missing       No
26841      Yes  Mandatory               Yes        B      Yes

[26842 rows x 5 columns]

#### Deal with some 'tricky' values in entries

In [49]:
set(bg_filtered['Textbook'].values)

{'Missing', 'N', 'No', 'Yes'}

#### Treat all 'N' as 'No'

In [50]:
N_index = []
for index, text_list in bg_filtered['Textbook'].items():
    if text_list == 'N':
        N_index.append(index)

In [51]:
bg_filtered['Textbook'][N_index] = 'No'

In [52]:
set(bg_filtered['Textbook'].values)

{'Missing', 'No', 'Yes'}

#### Grade

In [53]:
set(bg_filtered['Grade'].values)

{'A',
 'Audit',
 'B',
 'C',
 'D',
 'Drop',
 'F',
 'Incomplete',
 'Missing',
 'Not',
 'Rather'}

In [54]:
for index, text in bg_filtered['Grade'].items():
    if text == 'Not':
        bg_filtered['Grade'][index] = 'NotSure'
    if text == 'Audit':
        bg_filtered['Grade'][index] = 'AuditNoGrade'

In [55]:
set(bg_filtered['Grade'].values)

{'A',
 'AuditNoGrade',
 'B',
 'C',
 'D',
 'Drop',
 'F',
 'Incomplete',
 'Missing',
 'NotSure',
 'Rather'}

#### Let's look at how much entries having less than or equal to 1 `Missing` value

In [56]:
index_list = []
for index, value_list in bg_filtered.iterrows():
    i = 0
    for value in value_list:
        if value == 'Missing':
            i += 1
    if i <= 1:
        index_list.append(index)

In [57]:
len(index_list)

25273

#### Generally all entries are filled with enough information for deduction

In [58]:
df_new.insert(8, 'Credit', bg_filtered['Credit'])
df_new.insert(9, 'Attendance', bg_filtered['Attendance'])
df_new.insert(10, 'Student_TakeAgain', bg_filtered['Credit'])
df_new.insert(11, 'Grade', bg_filtered['Grade'])
df_new.insert(12, 'Textbook', bg_filtered['Textbook'])

df_new = df_new.drop(['Background'], axis = 1)
df_new

,Name,OverallRate,TakeAgain,Overall_Difficulty,Tags,Emotion,QualityRate,StudentDifficulty,Credit,Attendance,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,.Garcia,1.3,0.00,4.2,"['Lecture heavy', 'Tough grader', 'Get ready t...",awful,2.0,4.0,Yes,Mandatory,...,0,0,0,0,0,0,0,0,0,0
1,.Giordani,4.1,1.00,2.8,"['Beware of pop quizzes', 'Tough grader', 'Get...",awesome,5.0,3.0,Yes,Missing,...,0,1,0,0,1,0,0,0,0,0
2,.Heimgartner,4.2,1.00,1.6,"['Amazing lectures ', 'Clear grading criteria'...",awesome,5.0,3.0,Yes,Mandatory,...,0,0,0,0,0,1,0,0,0,0
3,.Huey,3.8,0.50,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awful,1.0,5.0,Yes,Missing,...,0,0,1,0,0,0,0,0,1,1
4,.Huey,3.8,0.50,3.1,"['Tough grader', 'Get ready to read', 'Tests a...",awesome,5.0,4.0,Yes,Not,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",average,3.0,2.0,Missing,Mandatory,...,0,0,0,0,0,0,0,0,0,0
26838,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,Yes,Mandatory,...,0,0,0,0,0,0,0,0,0,0
26839,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,2.0,Yes,Mandatory,...,0,0,0,0,0,0,0,0,0,0
26840,ZoilaMendoza,3.3,0.75,2.7,"['Caring', 'Clear grading criteria', 'Gives go...",awesome,5.0,1.0,Yes,Mandatory,...,0,0,0,0,0,0,0,0,0,0
26841,ZongDai,2.5,1.00,1.6,"['Participation matters', ""Skip class? You won...",awesome,4.0,4.0,Yes,Mandatory,...,0,0,0,0,1,0,1,0,0,0

In [59]:
df_new.to_csv('RMP_cleaned.csv', index=False)