In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./RMP_cleaned.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26842 entries, 0 to 26841
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      26842 non-null  object
 1   OverallRate               26842 non-null  float64
 2   TakeAgain                 26842 non-null  float64
 3   Overall_Difficulty        26842 non-null  float64
 4   Tags                      26842 non-null  object
 5   Emotion                   26842 non-null  object
 6   QualityRate               26842 non-null  float64
 7   StudentDifficulty         26842 non-null  float64
 8   Credit                    26842 non-null  object
 9   Attendance                26842 non-null  object
 10  Student_TakeAgain         26842 non-null  object
 11  Grade                     26842 non-null  object
 12  Textbook                  26842 non-null  object
 13  Comment                   26842 non-null  object
 14  accessible_outside_class  26842 non-null  int64
 15  amazing_lectures          26842 non-null  int64
 16  beware_of_pop_quizzes     26842 non-null  int64
 17  caring                    26842 non-null  int64
 18  clear_grading_criteria    26842 non-null  int64
 19  extra_credit              26842 non-null  int64
 20  get_ready_to_read         26842 non-null  int64
 21  gives_good_feedback       26842 non-null  int64
 22  graded_by_few_things      26842 non-null  int64
 23  group_projects            26842 non-null  int64
 24  hilarious                 26842 non-null  int64
 25  inspirational             26842 non-null  int64
 26  lecture_heavy             26842 non-null  int64
 27  lots_of_homework          26842 non-null  int64
 28  participation_matters     26842 non-null  int64
 29  respected                 26842 non-null  int64
 30  skip_class_you_wont_pass  26842 non-null  int64
 31  so_many_papers            26842 non-null  int64
 32  test_heavy                26842 non-null  int64
 33  tough_grader              26842 non-null  int64
dtypes: float64(5), int64(20), object(9)
memory usage: 7.0+ MB

In [6]:
df_modified = df.drop(['Name', 'OverallRate', 'TakeAgain', 'Overall_Difficulty', 'Tags', 'Emotion'], axis = 1)
df_modified

,QualityRate,StudentDifficulty,Credit,Attendance,Student_TakeAgain,Grade,Textbook,Comment,accessible_outside_class,amazing_lectures,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,2.0,4.0,Yes,Mandatory,Yes,A,Yes,The class was very intimidating at first. Howe...,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,3.0,Yes,Missing,Yes,Missing,Yes,Amazing woman. I wish every professor was like...,0,0,...,0,1,0,0,1,0,0,0,0,0
2,5.0,3.0,Yes,Mandatory,Yes,C,Yes,He was a great teacher and well respected by m...,0,1,...,0,0,0,0,0,1,0,0,0,0
3,1.0,5.0,Yes,Missing,Yes,Drop,Yes,I had to retake Biology and drop out of his cl...,0,0,...,0,0,1,0,0,0,0,0,1,1
4,5.0,4.0,Yes,Not,Yes,A,Yes,Best teacher that I have ever had. You will le...,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,3.0,2.0,Missing,Mandatory,Missing,A,No,She's cool. Kinda like a mom! Took her for the...,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,5.0,1.0,Yes,Mandatory,Yes,NotSure,No,"It's honestly just a pretty easy class, it's m...",0,0,...,0,0,0,0,0,0,0,0,0,0
26839,5.0,2.0,Yes,Mandatory,Yes,A,No,"she's really nice and understanding, and she's...",0,0,...,0,0,0,0,0,0,0,0,0,0
26840,5.0,1.0,Yes,Mandatory,Yes,Missing,No,Honestly one of the nicest professors you will...,0,0,...,0,0,0,0,0,0,0,0,0,0
26841,4.0,4.0,Yes,Mandatory,Yes,B,Yes,Be prepared for group work. A lot of people fe...,0,1,...,0,0,0,0,1,0,1,0,0,0

In [7]:
df_modified = df_modified.rename(columns={"StudentDifficulty": "Difficulty",
                                                                        "Student_TakeAgain": "TakeAgain"})

In [8]:
df_modified

,QualityRate,Difficulty,Credit,Attendance,TakeAgain,Grade,Textbook,Comment,accessible_outside_class,amazing_lectures,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,2.0,4.0,Yes,Mandatory,Yes,A,Yes,The class was very intimidating at first. Howe...,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,3.0,Yes,Missing,Yes,Missing,Yes,Amazing woman. I wish every professor was like...,0,0,...,0,1,0,0,1,0,0,0,0,0
2,5.0,3.0,Yes,Mandatory,Yes,C,Yes,He was a great teacher and well respected by m...,0,1,...,0,0,0,0,0,1,0,0,0,0
3,1.0,5.0,Yes,Missing,Yes,Drop,Yes,I had to retake Biology and drop out of his cl...,0,0,...,0,0,1,0,0,0,0,0,1,1
4,5.0,4.0,Yes,Not,Yes,A,Yes,Best teacher that I have ever had. You will le...,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,3.0,2.0,Missing,Mandatory,Missing,A,No,She's cool. Kinda like a mom! Took her for the...,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,5.0,1.0,Yes,Mandatory,Yes,NotSure,No,"It's honestly just a pretty easy class, it's m...",0,0,...,0,0,0,0,0,0,0,0,0,0
26839,5.0,2.0,Yes,Mandatory,Yes,A,No,"she's really nice and understanding, and she's...",0,0,...,0,0,0,0,0,0,0,0,0,0
26840,5.0,1.0,Yes,Mandatory,Yes,Missing,No,Honestly one of the nicest professors you will...,0,0,...,0,0,0,0,0,0,0,0,0,0
26841,4.0,4.0,Yes,Mandatory,Yes,B,Yes,Be prepared for group work. A lot of people fe...,0,1,...,0,0,0,0,1,0,1,0,0,0

In [9]:
df_modified['GoodTeaching'] = (df_modified['QualityRate'] > 3.0).astype('int64')
df_modified

,QualityRate,Difficulty,Credit,Attendance,TakeAgain,Grade,Textbook,Comment,accessible_outside_class,amazing_lectures,...,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader,GoodTeaching
0,2.0,4.0,Yes,Mandatory,Yes,A,Yes,The class was very intimidating at first. Howe...,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5.0,3.0,Yes,Missing,Yes,Missing,Yes,Amazing woman. I wish every professor was like...,0,0,...,1,0,0,1,0,0,0,0,0,1
2,5.0,3.0,Yes,Mandatory,Yes,C,Yes,He was a great teacher and well respected by m...,0,1,...,0,0,0,0,1,0,0,0,0,1
3,1.0,5.0,Yes,Missing,Yes,Drop,Yes,I had to retake Biology and drop out of his cl...,0,0,...,0,1,0,0,0,0,0,1,1,0
4,5.0,4.0,Yes,Not,Yes,A,Yes,Best teacher that I have ever had. You will le...,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,3.0,2.0,Missing,Mandatory,Missing,A,No,She's cool. Kinda like a mom! Took her for the...,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,5.0,1.0,Yes,Mandatory,Yes,NotSure,No,"It's honestly just a pretty easy class, it's m...",0,0,...,0,0,0,0,0,0,0,0,0,1
26839,5.0,2.0,Yes,Mandatory,Yes,A,No,"she's really nice and understanding, and she's...",0,0,...,0,0,0,0,0,0,0,0,0,1
26840,5.0,1.0,Yes,Mandatory,Yes,Missing,No,Honestly one of the nicest professors you will...,0,0,...,0,0,0,0,0,0,0,0,0,1
26841,4.0,4.0,Yes,Mandatory,Yes,B,Yes,Be prepared for group work. A lot of people fe...,0,1,...,0,0,0,1,0,1,0,0,0,1

In [10]:
df_modified.drop(['QualityRate'], axis = 1, inplace=True)
df_modified

,Difficulty,Credit,Attendance,TakeAgain,Grade,Textbook,Comment,accessible_outside_class,amazing_lectures,beware_of_pop_quizzes,...,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader,GoodTeaching
0,4.0,Yes,Mandatory,Yes,A,Yes,The class was very intimidating at first. Howe...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,3.0,Yes,Missing,Yes,Missing,Yes,Amazing woman. I wish every professor was like...,0,0,0,...,1,0,0,1,0,0,0,0,0,1
2,3.0,Yes,Mandatory,Yes,C,Yes,He was a great teacher and well respected by m...,0,1,0,...,0,0,0,0,1,0,0,0,0,1
3,5.0,Yes,Missing,Yes,Drop,Yes,I had to retake Biology and drop out of his cl...,0,0,0,...,0,1,0,0,0,0,0,1,1,0
4,4.0,Yes,Not,Yes,A,Yes,Best teacher that I have ever had. You will le...,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,2.0,Missing,Mandatory,Missing,A,No,She's cool. Kinda like a mom! Took her for the...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,1.0,Yes,Mandatory,Yes,NotSure,No,"It's honestly just a pretty easy class, it's m...",0,0,0,...,0,0,0,0,0,0,0,0,0,1
26839,2.0,Yes,Mandatory,Yes,A,No,"she's really nice and understanding, and she's...",0,0,0,...,0,0,0,0,0,0,0,0,0,1
26840,1.0,Yes,Mandatory,Yes,Missing,No,Honestly one of the nicest professors you will...,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26841,4.0,Yes,Mandatory,Yes,B,Yes,Be prepared for group work. A lot of people fe...,0,1,0,...,0,0,0,1,0,1,0,0,0,1

In [12]:
list(df_modified.columns)

['Difficulty',
 'Credit',
 'Attendance',
 'TakeAgain',
 'Grade',
 'Textbook',
 'Comment',
 'accessible_outside_class',
 'amazing_lectures',
 'beware_of_pop_quizzes',
 'caring',
 'clear_grading_criteria',
 'extra_credit',
 'get_ready_to_read',
 'gives_good_feedback',
 'graded_by_few_things',
 'group_projects',
 'hilarious',
 'inspirational',
 'lecture_heavy',
 'lots_of_homework',
 'participation_matters',
 'respected',
 'skip_class_you_wont_pass',
 'so_many_papers',
 'test_heavy',
 'tough_grader',
 'GoodTeaching']

In [18]:
col_names = list(df_modified.columns)
col_names.remove('GoodTeaching')
col_names.insert(0, 'GoodTeaching')
col_names

['GoodTeaching',
 'Difficulty',
 'Credit',
 'Attendance',
 'TakeAgain',
 'Grade',
 'Textbook',
 'Comment',
 'accessible_outside_class',
 'amazing_lectures',
 'beware_of_pop_quizzes',
 'caring',
 'clear_grading_criteria',
 'extra_credit',
 'get_ready_to_read',
 'gives_good_feedback',
 'graded_by_few_things',
 'group_projects',
 'hilarious',
 'inspirational',
 'lecture_heavy',
 'lots_of_homework',
 'participation_matters',
 'respected',
 'skip_class_you_wont_pass',
 'so_many_papers',
 'test_heavy',
 'tough_grader']

In [19]:
df_reindexed = df_modified[col_names]
df_reindexed

,GoodTeaching,Difficulty,Credit,Attendance,TakeAgain,Grade,Textbook,Comment,accessible_outside_class,amazing_lectures,...,hilarious,inspirational,lecture_heavy,lots_of_homework,participation_matters,respected,skip_class_you_wont_pass,so_many_papers,test_heavy,tough_grader
0,0,4.0,Yes,Mandatory,Yes,A,Yes,The class was very intimidating at first. Howe...,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,3.0,Yes,Missing,Yes,Missing,Yes,Amazing woman. I wish every professor was like...,0,0,...,0,1,0,0,1,0,0,0,0,0
2,1,3.0,Yes,Mandatory,Yes,C,Yes,He was a great teacher and well respected by m...,0,1,...,0,0,0,0,0,1,0,0,0,0
3,0,5.0,Yes,Missing,Yes,Drop,Yes,I had to retake Biology and drop out of his cl...,0,0,...,0,0,1,0,0,0,0,0,1,1
4,1,4.0,Yes,Not,Yes,A,Yes,Best teacher that I have ever had. You will le...,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26837,0,2.0,Missing,Mandatory,Missing,A,No,She's cool. Kinda like a mom! Took her for the...,0,0,...,0,0,0,0,0,0,0,0,0,0
26838,1,1.0,Yes,Mandatory,Yes,NotSure,No,"It's honestly just a pretty easy class, it's m...",0,0,...,0,0,0,0,0,0,0,0,0,0
26839,1,2.0,Yes,Mandatory,Yes,A,No,"she's really nice and understanding, and she's...",0,0,...,0,0,0,0,0,0,0,0,0,0
26840,1,1.0,Yes,Mandatory,Yes,Missing,No,Honestly one of the nicest professors you will...,0,0,...,0,0,0,0,0,0,0,0,0,0
26841,1,4.0,Yes,Mandatory,Yes,B,Yes,Be prepared for group work. A lot of people fe...,0,1,...,0,0,0,0,1,0,1,0,0,0

In [21]:
df_reindexed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26842 entries, 0 to 26841
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   GoodTeaching              26842 non-null  int64
 1   Difficulty                26842 non-null  float64
 2   Credit                    26842 non-null  object
 3   Attendance                26842 non-null  object
 4   TakeAgain                 26842 non-null  object
 5   Grade                     26842 non-null  object
 6   Textbook                  26842 non-null  object
 7   Comment                   26842 non-null  object
 8   accessible_outside_class  26842 non-null  int64
 9   amazing_lectures          26842 non-null  int64
 10  beware_of_pop_quizzes     26842 non-null  int64
 11  caring                    26842 non-null  int64
 12  clear_grading_criteria    26842 non-null  int64
 13  extra_credit              26842 non-null  int64
 14  get_ready_to_read         26842 non-null  int64
 15  gives_good_feedback       26842 non-null  int64
 16  graded_by_few_things      26842 non-null  int64
 17  group_projects            26842 non-null  int64
 18  hilarious                 26842 non-null  int64
 19  inspirational             26842 non-null  int64
 20  lecture_heavy             26842 non-null  int64
 21  lots_of_homework          26842 non-null  int64
 22  participation_matters     26842 non-null  int64
 23  respected                 26842 non-null  int64
 24  skip_class_you_wont_pass  26842 non-null  int64
 25  so_many_papers            26842 non-null  int64
 26  test_heavy                26842 non-null  int64
 27  tough_grader              26842 non-null  int64
dtypes: float64(1), int64(21), object(6)
memory usage: 5.7+ MB

In [22]:
comment_df = df_reindexed[['GoodTeaching', 'Comment']]
comment_df

       GoodTeaching                                            Comment
0                 0  The class was very intimidating at first. Howe...
1                 1  Amazing woman. I wish every professor was like...
2                 1  He was a great teacher and well respected by m...
3                 0  I had to retake Biology and drop out of his cl...
4                 1  Best teacher that I have ever had. You will le...
...             ...                                                ...
26837             0  She's cool. Kinda like a mom! Took her for the...
26838             1  It's honestly just a pretty easy class, it's m...
26839             1  she's really nice and understanding, and she's...
26840             1  Honestly one of the nicest professors you will...
26841             1  Be prepared for group work. A lot of people fe...

[26842 rows x 2 columns]

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_reindexed.iloc[:, 1:], df_reindexed['GoodTeaching'], 
                                                    test_size=0.25, stratify=df_reindexed['GoodTeaching'], random_state=24)

In [26]:
X_train.shape, X_test.shape

((20131, 27), (6711, 27))

In [33]:
train_df = pd.concat([y_train, X_train], axis = 1)
test_df = pd.concat([y_test, X_test], axis = 1)

In [38]:
comment_train = train_df[['GoodTeaching', 'Comment']]
comment_test = test_df[['GoodTeaching', 'Comment']]

In [43]:
train_df.drop(['Comment'], axis = 1, inplace=True)
test_df.drop(['Comment'], axis = 1, inplace=True)

In [46]:
train_df.to_csv('./rmp_train.csv', index=False)
test_df.to_csv('./rmp_test.csv', index=False)

comment_train.to_csv('./comment_train.csv', index=False)
comment_test.to_csv('./comment_test.csv', index=False)